.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BERKELEY-ABC 1 "September 14, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
berkeley-abc \-  A System for Sequential Synthesis and Verification 
.SH SYNOPSIS
.B berkeley-abc
.RI [ options ] " <infile>"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B berkeley-abc
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBberkeley-abc\fP is a program that synthesizes RTL to gate-level logic.
.SH OPTIONS
A summary of options is included below.
.\".TP
.\".B \-q
.\"quiet operation. only write error message to console
.SH AUTHOR
berkeley-abc was written by Berkeley Logic Synthesis and Verification Group.
.PP
This manual page was written by Ruben Undheim <ruben.undheim@gmail.com>,
for the Debian project (and may be used by others).
